version: '3.1'

services:

  web:
    image: nginx:alpine
    networks:
      - frontend

  app:
    image: nginx:alpine
    networks:
      - frontend
      - backend

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
    networks:
      - backend

networks:
  frontend:
  backend:

