version: '3.1'

services:

  web:
    image: nginx:alpine
    networks:
      - frontend

  app:
    image: nginx:alpine
    networks:
      - frontend
      - backend

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    networks:
      - backend
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  frontend:
  backend:

volumes:
  mysql_data:

